/**
 * Lint rules chosen for the bugs this codebase can actually have.
 *
 * The app is a single-page tool whose correctness lives in three places: a
 * numeric solver, a graph resolver, and a pile of React effects that push CSS
 * into an iframe. Type errors are already caught by `tsc --strict`, so the rules
 * that earn their place here are the ones a type checker cannot see:
 *
 *   - `react-hooks/exhaustive-deps` — the effects in SnapshotFrame and PaletteWall
 *     coordinate an iframe by hand. A missing dependency there is a stale preview,
 *     which is the one failure mode this tool must not have.
 *   - `no-floating-promises` and `no-misused-promises` — `decodeSpecFromHash`,
 *     the clipboard writes and the dynamic imports all return promises that were
 *     being dropped. A swallowed rejection here is a silent no-op.
 *   - `consistent-type-imports` — the codebase already writes `import type`
 *     everywhere by hand; this stops it drifting.
 *
 * Type-aware linting is on (`projectService`), which is slower but is the only way
 * the promise rules work at all.
 */

import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
    {
        // Vendored design-system data and build output are not ours to lint.
        ignores: ['dist/**', 'vendor/**', 'public/vendor/**', 'coverage/**'],
    },

    js.configs.recommended,
    ...tseslint.configs.recommendedTypeChecked,

    {
        languageOptions: {
            parserOptions: {
                projectService: true,
                tsconfigRootDir: import.meta.dirname,
            },
        },
    },

    // --- the app ----------------------------------------------------------
    {
        files: ['src/**/*.{ts,tsx}'],
        plugins: {
            'react-hooks': reactHooks,
            'react-refresh': reactRefresh,
        },
        rules: {
            ...reactHooks.configs.recommended.rules,
            'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

            '@typescript-eslint/consistent-type-imports': [
                'error',
                { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
            ],
            '@typescript-eslint/no-floating-promises': 'error',
            '@typescript-eslint/no-misused-promises': 'error',

            // An unused argument named `_` is how several callbacks here declare
            // "this parameter exists for position only".
            '@typescript-eslint/no-unused-vars': [
                'error',
                { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
            ],

            // The vendored JSON genuinely arrives untyped, and the casts that
            // narrow it are load-bearing. Flag them as warnings so new ones are
            // visible without failing the build on the existing, documented ones.
            '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
            '@typescript-eslint/no-explicit-any': 'error',
        },
    },

    // --- plain JavaScript -------------------------------------------------
    // The sync script and its helpers are `.mjs` on purpose: they run under bare
    // node, before anything is built. They are outside the TS project, so the
    // type-aware rules cannot see them and must be switched off rather than left
    // to fail with a parser error on every file.
    {
        files: ['**/*.{js,mjs,cjs}'],
        ...tseslint.configs.disableTypeChecked,
    },

    // --- node-side scripts ------------------------------------------------
    // These run under vite-node or plain node, print to a terminal and are
    // allowed to be imperative about it.
    {
        files: ['scripts/**/*.{ts,mjs}', '*.config.{ts,js}'],
        languageOptions: {
            globals: globals.node,
        },
        rules: {
            'no-console': 'off',
            '@typescript-eslint/no-unsafe-assignment': 'off',
            '@typescript-eslint/no-unsafe-member-access': 'off',
            '@typescript-eslint/no-unsafe-argument': 'off',
            '@typescript-eslint/no-unsafe-call': 'off',
        },
    },

    // Tests reach into internals on purpose.
    {
        files: ['src/**/__tests__/**/*.{ts,tsx}'],
        rules: {
            '@typescript-eslint/no-unsafe-assignment': 'off',
            '@typescript-eslint/no-unsafe-member-access': 'off',
        },
    },

    /*
       Generated by `npx shadcn@latest add`, and kept close to upstream so the
       command can be re-run to pick up a fix without hand-merging.

       shadcn's own shape exports a `cva` variants object next to the component —
       `buttonVariants`, `badgeVariants`, `toggleVariants` — which react-refresh
       objects to. Exempting the directory is the honest fix: rewriting the files
       to satisfy the rule would make every future `shadcn add` produce a diff
       against our edits rather than against upstream.
    */
    {
        files: ['src/components/ui/**/*.tsx'],
        rules: {
            'react-refresh/only-export-components': 'off',
        },
    },

    // Must come last: turns off every rule Prettier owns.
    prettier,
);
