/**
 * Emit the token layer as CSS — WITH var() chains.
 *
 * This is the whole technical premise of the app. The design system's Style
 * Dictionary config does not set `outputReferences: true`, so the CSS it ships
 * is fully flattened: `--sys-color-surface-notification: #FF6726`, never
 * `var(--ref-palette-orange-500)`. Not one right-hand side in
 * desktop_variables.css contains a var(). Overriding a --ref-* against that CSS
 * therefore does nothing at all.
 *
 * Here, an alias emits an actual var() reference. That single difference is what
 * makes a palette edit cascade ref -> sys -> comp -> painted component, live.
 *
 * The payoff for the update path is large and worth stating: because aliases are
 * emitted as var() TEXT, they never need re-pushing when the palette moves.
 * A full palette re-solve changes exactly the 66 reference hexes; everything
 * downstream re-resolves in the browser's own cascade, for free.
 */

import type { PaletteSolution } from '../engine/types';
import type { Resolved } from '../model/resolve';
import { rungToNodeId } from '../model/resolve';
import type { NodeId, TokenGraph } from '../model/types';

export interface EmitOptions {
    /** Sparse alias repoints layered over the vendored graph. */
    aliasOverrides?: Map<NodeId, NodeId>;
    /** Emitted as a comment header. */
    header?: string;
}

/**
 * The full token block, suitable for injecting into the preview or exporting.
 *
 * Only tokens the app manages are emitted; the vendored desktop_variables.css
 * is loaded underneath as a base layer and supplies everything else (spacing,
 * radius, typography, motion, and the V2 palette the component CSS still
 * needs). Emitting only what we manage means a non-colour token can never be
 * wrong because of this app.
 */
export function emitTokenCss(
    graph: TokenGraph,
    resolved: Resolved,
    solution: PaletteSolution,
    options: EmitOptions = {},
): string {
    const { aliasOverrides, header } = options;
    const lines: string[] = [];

    if (header) lines.push(`/* ${header} */`);
    lines.push(
        '/* Generated by Agorapulse Color Lab.',
        ' * Aliases are emitted as var() references — this is what the design system',
        ' * would produce with `outputReferences: true` in desktop_config.js, and what',
        ' * makes a reference edit cascade into components at runtime.',
        ' */',
        ':root {',
    );

    // --- 1. the engine-owned reference rungs -------------------------------
    lines.push('  /* reference palette — solved from anchors and constraints */');
    for (const [rung, solved] of solution.rungs) {
        const node = graph.nodes.get(rungToNodeId(rung));
        if (!node) continue;
        lines.push(`  ${node.cssVar}: ${solved.hex};`);
    }

    // --- 2. every other managed token, as a var() chain --------------------
    const emitTier = (tier: 'sys' | 'comp', label: string) => {
        const rows: string[] = [];
        for (const id of graph.topoOrder) {
            const node = graph.nodes.get(id);
            if (!node || node.tier !== tier || !node.isColor) continue;
            // The legacy V2 intent layer is read-only and already correct in the
            // base stylesheet; re-emitting it would just add noise.
            if (node.palette === 'v2') continue;

            const override = aliasOverrides?.get(id);
            const target =
                override ?? (node.source.kind === 'alias' ? node.source.target : undefined);

            if (target !== undefined) {
                const targetNode = graph.nodes.get(target);
                if (targetNode) {
                    rows.push(`  ${node.cssVar}: var(${targetNode.cssVar});`);
                    continue;
                }
            }
            const value = resolved.get(id)?.value;
            if (value) rows.push(`  ${node.cssVar}: ${value};`);
        }
        if (rows.length) {
            lines.push('', `  /* ${label} */`, ...rows);
        }
    };

    emitTier('sys', 'semantic layer');
    emitTier('comp', 'component layer');

    /*
       A third section used to sit here: an optional block re-aliasing every V2 name onto its
       nearest V3 rung by OKLab distance, so a preview of the real components would respond to
       V3 edits. It went with the migration workbench — there is no component preview in this
       tool and no `vendor/manifest.json` to read the leak audit from.

       What that block emitted was a SIMULATION, and it is worth saying so once: it answered
       "what would this palette look like if the migration were finished", which is a different
       question from "what does this palette export to". Only the second one is asked here.
    */

    lines.push('}');
    return lines.join('\n') + '\n';
}

/**
 * The properties that change when the palette re-solves: the 66 reference rungs
 * and nothing else.
 *
 * This is the per-frame payload during an anchor drag. Aliases are already
 * var() text in the stylesheet, so they are absent here by design — the browser
 * re-resolves them itself. 66 setProperty calls per frame, no stylesheet
 * re-parse, no selector re-matching.
 */
export function paletteDeltas(
    graph: TokenGraph,
    solution: PaletteSolution,
): Array<[string, string]> {
    const out: Array<[string, string]> = [];
    for (const [rung, solved] of solution.rungs) {
        const node = graph.nodes.get(rungToNodeId(rung));
        if (node) out.push([node.cssVar, solved.hex]);
    }
    return out;
}

/**
 * The one-line upstream fix this whole architecture works around.
 * Surfaced in the UI next to the CSS export, because it is arguably the most
 * valuable thing this project uncovers.
 */
export const UPSTREAM_FIX = {
    file: 'libs/ui-theme/src/desktop_config.js',
    change: 'add `options: { outputReferences: true }` to the css/variables file entry',
    why:
        'Without it every alias is flattened at build time, so the shipped CSS cannot ' +
        'cascade: changing a reference token at runtime has no effect on anything. ' +
        'With it, the CSS the design system already ships behaves the way this app has ' +
        'to reconstruct by hand.',
} as const;
